src/Entity/Panier.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PanierRepository")
 */
class Panier
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Produits", inversedBy="paniers")
     */
    private $produit;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantite_commande;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_ajout;

    /**
     * @ORM\Column(type="boolean")
     */
    private $etat;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProduit(): ?Produits
    {
        return $this->produit;
    }

    public function setProduit(?Produits $produit): self
    {
        $this->produit = $produit;

        return $this;
    }

    public function getQuantiteCommande(): ?int
    {
        return $this->quantite_commande;
    }

    public function setQuantiteCommande(int $quantite_commande): self
    {
        $this->quantite_commande = $quantite_commande;

        return $this;
    }

    public function getDateAjout(): ?\DateTimeInterface
    {
        return $this->date_ajout;
    }

    public function setDateAjout(\DateTimeInterface $date_ajout): self
    {
        $this->date_ajout = $date_ajout;

        return $this;
    }

    public function getEtat(): ?bool
    {
        return $this->etat;
    }

    public function setEtat(bool $etat): self
    {
        $this->etat = $etat;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Panier;
use App\Entity\Produits;
use App\Form\AddPanierType;
use App\Form\AddProduitType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
  /**
   * @Route("/produits", name="produits")
   */
  public function index(Request $request, EntityManagerInterface $entityManager)
  {
    $produit = new Produits();
    $produitRepository = $this->getDoctrine()->getRepository(Produits::class)->findAll();

    $form = $this->createForm(AddProduitType::class, $produit);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
      $produit = $form->getData();

      $photo = $produit->getPhoto();
      $photoName = md5(uniqid()) . '.' . $photo->guessExtension();
      $photo->move($this->getParameter('upload_files'), $photoName);
      $produit->setPhoto($photoName);

      $entityManager->persist($produit);
      $entityManager->flush();

      return $this->redirectToRoute('panier');


    }

    return $this->render('main/index.html.twig', [
      'produits' => $produitRepository,
      'addProduit' => $form->createView()
    ]);

  }

  /**
   * @Route("/fiche/produit/{id}", name="ficheProduit")
   */

  public function ficheProduit($id,EntityManagerInterface $entityManager, Request $request)
  {
    $singleProduit = $this->getDoctrine()->getRepository(Produits::class)->find($id);

    $paniers= new Panier();

    $panierRepository=$this->getDoctrine()->getRepository(Panier::class)->findAll();

    $form = $this->createForm(AddPanierType::class, $paniers);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
    $paniers = $form->getData();

    $paniers->setDateAjout(new \DateTime());
    $paniers->setEtat(false);
    $paniers->setProduit($singleProduit);

    $entityManager->persist($paniers);
    $entityManager->flush();

      return $this->redirectToRoute('panier');


    }
    return $this->render('main/ficheProduit.html.twig', [
      'produit' => $singleProduit,
      'paniers'=>$panierRepository,
      'formPanier'=>$form->createView()

    ]);

  }

  /**
   * @Route("/produit/remove/{id}", name="removeProduit")
   */
  public function removeProduit($id, EntityManagerInterface $entityManager)
  {
    $produit = $this->getDoctrine()->getRepository(Produits::class)->find($id);

    $entityManager->remove($produit);
    $entityManager->flush();

    return $this->redirectToRoute('produits');
  }
  /**
   * @Route("/", name="panier")
   */
  public function acceuil()
  {
    $paniers=$this->getDoctrine()->getRepository(Panier::class)->findAll();

    $panierTotal = 0;

    foreach ($paniers as $panier){
      $panierTotal += ($panier->getProduit()->getPrix() * $panier->getQuantiteCommande());
    }

    return $this->render('main/panier.html.twig', [
      'paniers' => $paniers,
      'panierTotal'=>$panierTotal

    ]);
  }
  /**
   * @Route("/panier/remove/{id}", name="removePanier")
   */
  public function removePanier($id, EntityManagerInterface $entityManager)
  {
    $paniers = $this->getDoctrine()->getRepository(Panier::class)->find($id);

    $entityManager->remove($paniers);
    $entityManager->flush();

    return $this->redirectToRoute('panier');
  }


}

templates/main/ficheProduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
  <table class="table table-dark">
    <thead>
    <tr>
      <th scope="col">{% trans %}Nom{% endtrans %}</th>
      <th scope="col">{% trans %}Photo{% endtrans %}</th>
      <th scope="col">{% trans %}Quantité{% endtrans %}</th>
      <th scope="col">{% trans %}Prix{% endtrans %}</th>
      <th>{% trans %}Suppression{% endtrans %}</th>
    </tr>
    </thead>
      <tbody>
      <tr>
        <th scope="row">{{ produit.nom }}</th>
        <td><img src="{{ asset('/uploads/upload_files/' ~ produit.photo)}}" ></td>
        <td>{{ produit.quantite }}</td>
        <td>{{ produit.prix }} €</td>
        <td><a href="{{path("removeProduit",{id: produit.id})}}"><button class="btn btn-danger">{% trans %}Supprimer{% endtrans %}</button></a></td>
      </tr>
      </tbody>
  </table>
  {{form_start(formPanier)}}
  {{ form_end(formPanier)}}
{% endblock %}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}
{{ form_start(addProduit) }}
 {{ form_end(addProduit) }}

  <table class="table table-dark">
    <thead>
    <tr>
      <th scope="col">{% trans %}Nom{% endtrans %}</th>
      <th scope="col">{% trans %}Photo{% endtrans %}</th>
      <th scope="col">{% trans %}Quantité{% endtrans %}</th>
      <th scope="col">{% trans %}Prix{% endtrans %}</th>
    </tr>
    </thead>
    {% for produit in produits %}

    <tbody>
    <tr>
      <th scope="row"><a href="{{path("ficheProduit", {id: produit.id})}}">{{ produit.nom }}</a></th>
      <td><img src="{{ asset('/uploads/upload_files/' ~ produit.photo)}}" ></td>
      <td>{{ produit.quantite }}</td>
      <td>{{ produit.prix }} €</td>

    </tr>
    </tbody>

    {% endfor %}

  </table>

{% endblock %}

templates/main/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}

{% block body %}

  <table class="table table-dark">
    <thead>
    <tr>
      <th scope="col">{% trans %}Nom{% endtrans %}</th>
      <th scope="col">{% trans %}Quantité commandée{% endtrans %}</th>
      <th scope="col">{% trans %}Montant {% endtrans %}</th>
      <th scope="col">{% trans %}Date d'ajout{% endtrans %}</th>
      <th scope="col">{% trans %}Suppression{% endtrans %}</th>
    </tr>
    </thead>

      <tbody>

      {% for panier in paniers %}
      <tr>
        <td>{{ panier.produit.nom }}</td>
        <td>{{ panier|length }}</td>
        <td>{{ panier|length * panier.produit.prix}} €</td>
        <td>{{ panier.dateAjout| date('Y-m-d')}}</td>
        <td><a href="{{path("removePanier",{id: panier.id})}}"><button class="btn btn-danger">{% trans %}Supprimer{% endtrans %}</button></a></td>

      </tr>
      {% endfor %}
      <tr>
        <td>({{ paniers|length }} {% trans %}produits{% endtrans %}) </td>
        <td></td>
        <td>{{ panierTotal }} €</td>
      </tr>
      </tbody>
  </table>

{% endblock %}